version: '3.8'

services:
  qbit-peers-mariadb:
    image: mariadb:latest
    container_name: qbit-peers-mariadb
    volumes: # Change /opt/qbit-peers to your desired location
      - /opt/qbit-peers/data:/var/lib/mysql
      - /opt/qbit-peers/init-scripts:/docker-entrypoint-initdb.d
      - /opt/qbit-peers/data/IP2LOCATION-LITE-DB5.CSV:/tmp/IP2LOCATION-LITE-DB5.CSV
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: ip2location
    # Add any additional compose requirements here

  qbit-peers:
    image: python:3.9
    container_name: qbit-peers
    volumes: # Change /opt/qbit-peers to your desired location
      - /opt/qbit-peers/qbit-peers.py:/app/qbit-peers.py
      - /opt/qbit-peers/requirements.txt:/app/requirements.txt
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python qbit-peers.py"
    # Add any additional compose requirements here
